services:
  db:
    build: ./requirements/mariadb
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    networks:
      - wp-network
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  php:
    build: ./requirements/wordpress
    env_file:
      - .env
    secrets:
      - db_password
      - wp_admin_password
      - wp_second_user_password
    networks:
      - wp-network
    volumes:
      - wp_data:/var/www/html:rw
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html:rw
      - ../secrets/certs:/etc/nginx/ssl:ro
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php
    networks:
      - wp-network
    restart: unless-stopped

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_second_user_password:
    file: ../secrets/wp_second_user_password.txt

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/amugisha/data/wp
      o: bind
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/amugisha/data/db
      o: bind


networks:
  wp-network:
    driver: bridge
